### ISSUE TITLE
Getting "'args' is not defined" in idifference2.py 

### ISSUE THREAD

**Issue by pr3l14t0r** [dfxml-working-group/dfxml_python#22]
Heyho together! 
I am using the script `idifference2.py` in my master-thesis, but since i am working on the most current version of the code, i am receiving the following error: 

Command: 
```bash
python3 /DFXML/dfxml_python/dfxml/bin/idifference2.py -x /images/FileModifications_02/Testfile.idiff /images/kubernetes-worker-1_INIT.raw /images/FileModifications_02/kubernetes-worker-1_FileModifications_02.15.raw
```

Response:
```text
INFO:idifference2.py:>>> Reading kubernetes-master-1_INIT.raw.
INFO:idifference2.py:>>> Reading FileModifications_02/kubernetes-master-1_FileModifications_02.12.raw.
Traceback (most recent call last):
  File "/DFXML/dfxml_python/dfxml/bin/idifference2.py", line 117, in <module>
    main()
  File "/DFXML/dfxml_python/dfxml/bin/idifference2.py", line 96, in main
    diffdfxml = make_differential_dfxml.make_differential_dfxml(
  File "/DFXML/dfxml_python/dfxml/bin/make_differential_dfxml.py", line 213, in make_differential_dfxml
    if ignore_filename_function(new_obj.filename):
  File "/DFXML/dfxml_python/dfxml/bin/idifference2.py", line 36, in ignorable_name
    if args.include_dotdirs and os.path.basename(fn) in [".", ".."]:
NameError: name 'args' is not defined
```

The latest commit i was succesfully working on is `f6bfaa0f0980fe729a9c30d9ea3a6810143244fa`. When switching back via `git reset f6bfaa0f0980fe729a9c30d9ea3a6810143244fa --hard`, the same command is working flawlessly. 

I am using sleuthkit and dfxml in a docker container, but also do receive this error in a normal bash commandline. 

I'd try to solve that on my own but i am not that deep into the source code right now and therefore can't tell what the function `ignorable_name(fn)` is trying to achieve. But as the error message already states, `args` is not defined. :D 

I'd highly appreciate it if you can help out here. I am trying to resolve that as well on my own and will come up with a solution, in case i find any. 

Thanks anyways for your great efforts and for keeping up this wonderful project!

**Comment by simsong** [comment]
Hi. IYou should do a clean checkout and see if the error happens there.  `idifference2.py` is inheriting `args` from the runtime environment using python's dynamic scoping rules:

https://github.com/dfxml-working-group/dfxml_python/blob/7f0a5c74051bf2fd80109e948e3adf3222d195ae/dfxml/bin/idifference2.py#L36

You should modify `ignorable_name(fn)` to take `args.include_dotdirs` as an argument, and then pass the argument in when it is called. Please do so, test it, and then submit a pull request.

**Comment by jgru** [comment]
Hi, this bug stemmed from my previous effort to introduce a separate `main()`-function with the intent to install the script `idifference2.py` via `setup.cfg`'s `console_scripts` in the future. Pull request #23 should fix this regression bug. 
Sorry for the inconvenience.

**Comment by jgru** [comment]
> I just added idifference2.py to the check-mypy target in PR 24. I confirmed this would have been found this if type signatures had been started on that script.

This is very valuable. Thanks for adding this "testcase", the type annotations and the cleaned up imports, @ajnelson-nist. 
I think some kind of SEMVER-versioned release would have been helpful for @pr3l14t0r and other users.
Which are the needed steps until a tagged released could be created?

Best regars
Jan
